### ISSUE TITLE
Suppress warnings in FSNano33BLE.h

### ISSUE THREAD

**Issue by cpetra** [khoih-prog/FS_Nano33BLE#7]
### Is your feature request related to a problem? Please describe.
I like the library, and it's exactly what I needed so far, great work!
It is, though, a bit annoying seeing warnings like this when compiling the code (and can also make "real" warnings harder to find):
```
#warning Using default NANO33BLE_FS_SIZE_KB == 64KB
```
### Describe the solution you'd like
Guarding these defines with something optional like "#ifdef FS_VERBOSE" would be sufficient.

### Describe alternatives you've considered
Could also use something like "FS_WARN_SUPPRESS" to invert the logic from the above solution (ioptional flag to suppress the warnings explicitly). 

### Additional context

![image](https://user-images.githubusercontent.com/3313221/174657367-ebb111de-0fa1-45c8-a634-15536b59d800.png)

**Comment by khoih-prog** [comment]
Hi @cpetra 

As you know, this `outdated` library was written for all types of users, from sophisticated one to beginners. To let the users, me too when users post the issue, know if there is something wrong with the settings, configurations.

For sophisticated users like you, it's **extremely easy to modify once-for-all** the library by comment out, #ifdef, etc to disable the warnings.

I still haven't got time to modify too many libraries, to use optional `warnings` such as I did in some libs

https://github.com/khoih-prog/ESP_WiFiManager/blob/69ec6b3e686485f04364277c6172e4a29ea64dce/src/ESP_WiFiManager.hpp#L48-L53

```
#if (_WIFIMGR_LOGLEVEL_ > 3)
	#if ( defined(ESP_ARDUINO_VERSION_MAJOR) && (ESP_ARDUINO_VERSION_MAJOR >= 2) )
	  #warning Using ESP32_C3 using core v2.0.0+. Either LittleFS, SPIFFS or EEPROM OK.
	#else
	  #warning Using ESP32_C3 using core v1.0.6-. To follow library instructions to install esp32-c3 core. Only SPIFFS and EEPROM OK.
	#endif
#endif
```

Anyway, I'll try to update all libraries with the new `optional warnings`, time-permitted.

Thanks anyway,

**Comment by cpetra** [comment]
Hi @khoih-prog,

Thanks for the answer. Yes, it is really easy to modify the code, but unfortunately not **once-for-all** as I actually like integrating existing libraries without modifying them as it is safer long-term. Anyway, I'm also not considering myself a sophisticated user (did I feel some sarcasm here?). 

Thanks for sharing anyway.

Regards

**Comment by khoih-prog** [comment]
Hi @cpetra 

The new [**FS_Nano33BLE** v1.2.1](https://github.com/khoih-prog/FS_Nano33BLE/releases/tag/v1.2.1) has just been published to address your issue as well as to support more boards.

Best Regards,

---

### Releases v1.2.1

1. Add support to Seeeduino nRF52840-based boards such as **SEEED_XIAO_NRF52840 and SEEED_XIAO_NRF52840_SENSE**, etc. using Seeeduino `mbed` core
2. Add astyle using `allman` style. Restyle the library
3. Display compile warning only when `_FS_LOGLEVEL_ > 3`
