### ISSUE TITLE
Impossibile to create a class

### ISSUE THREAD

**Issue by Sladerix** [khoih-prog/FS_Nano33BLE#8]
Hi, I'm using a Seeeduino XIAO BLE board (it mounts nRF52840).
I edited the ".h" file to bypass the board check, given the fact that it is not listed in it.

However, when I run the example code, everything works as expected.

Then I decided to try to make a class out of it (**ProjectA**), in order to make my work easier. 
So I begin to copy/paste block of code from the example to a blank project.

I managed to implement also ArduinoJson and vector.
It seemed to work fine till the end.

THAN the WTF moment kicks in...
I put the _.hpp_ and _.cpp_ files in another project (**ProjectB**) to use the "library" I just made and BOOM nothing works anymore! Exact code.

So I tried to flash back the **ProjectA** it was working a while ago => it stopped working too     O_o

So... I tried to upload your example code and worked. At this point I'm confused.

I attach the **ProjectA** that was actually working (I made several intermediate tests ArduinoJson was working good)
[XiaoFS_Example.zip](https://github.com/khoih-prog/FS_Nano33BLE/files/9846422/XiaoFS_Example.zip)

**Comment by khoih-prog** [comment]
Hi @Sladerix 

> However, when I run the example code, everything works as expected.

Sorry I don't have time to help you in this, **unless you prove that this is a bug of the library.**

I suggest you post the issue on Arduino Forum or any programming Forum and ask for help. Remember to post everything (your code, steps how to duplicate the issue, etc.) so that anybody can verify.

Good Luck,

**Comment by Sladerix** [comment]
> Hi @Sladerix
> 
> > However, when I run the example code, everything works as expected.
> 
> Sorry I don't have time to help you in this, **unless you prove that this is a bug of the library.**
> 
> I suggest you post the issue on Arduino Forum or any programming Forum and ask for help. Remember to post everything (your code, steps how to duplicate the issue, etc.) so that anybody can verify.
> 
> Good Luck,

Well.. the fact that the same exact code has two different results is quite strange… above all if for a moment it worked… 

to me gives “Failed” on “fopen”

**Comment by khoih-prog** [comment]
Hi @Sladerix 

FYI, the new [**FS_Nano33BLE** v1.2.1](https://github.com/khoih-prog/FS_Nano33BLE/releases/tag/v1.2.1) has just been published to  support more boards such as **SEEED_XIAO_NRF52840 and SEEED_XIAO_NRF52840_SENSE**, etc. using Seeeduino `mbed` core

Best Regards,

---

### Releases v1.2.1

1. Add support to Seeeduino nRF52840-based boards such as **SEEED_XIAO_NRF52840 and SEEED_XIAO_NRF52840_SENSE**, etc. using Seeeduino `mbed` core
2. Add astyle using `allman` style. Restyle the library
3. Display compile warning only when `_FS_LOGLEVEL_ > 3`

**Comment by Sladerix** [comment]
> Hi @Sladerix
> 
> FYI, the new [**FS_Nano33BLE** v1.2.1](https://github.com/khoih-prog/FS_Nano33BLE/releases/tag/v1.2.1) has just been published to support more boards such as **SEEED_XIAO_NRF52840 and SEEED_XIAO_NRF52840_SENSE**, etc. using Seeeduino `mbed` core
> 
> Best Regards,
> 
> ### Releases v1.2.1
> 1. Add support to Seeeduino nRF52840-based boards such as **SEEED_XIAO_NRF52840 and SEEED_XIAO_NRF52840_SENSE**, etc. using Seeeduino `mbed` core
> 2. Add astyle using `allman` style. Restyle the library
> 3. Display compile warning only when `_FS_LOGLEVEL_ > 3`

Thank you very much for the effort!!

Unfortunately the class source code I uploaded in the first post still gives this error:
<img width="954" alt="Schermata 2022-10-26 alle 08 45 16" src="https://user-images.githubusercontent.com/6717214/197953998-955ee436-a864-4274-ae29-de0172d93d3f.png">

At the moment I'm dealing with it by simply not wrapping it into a class, but putting the various functions in the main code (like in the example).
I would like to have a functioning class to have the code more tidy and simply to read (and more important, modular to use than in other projects) 

At the moment I'm working on a project where I've to be fast to finish.. so for now I will leave it like that, in future i can look more deep and hope to find something 

Thank you
